[package]
name = "deep-spotify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "~1.7"
regex = "~1.9"
serde = { version = "~1.0", features = ["derive"] }
serde_json = "1.0.106"
zip = "~0.6"
